### ISSUE TITLE
mysql 

### ISSUE THREAD

**Issue by Hemdon** [bubbajames-docker/sendy#1]
Hi James,

For some reason mysql is not starting. I am getting following error when hit the sendy browser.

Can't connect to database
There is a problem connecting to the database. Please try again later or see this troubleshooting tip.

root@21e39f251a3a:/var/log/apt# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 21:46 ?        00:00:00 apache2 -DFOREGROUND
www-data    33     1  0 21:46 ?        00:00:00 apache2 -DFOREGROUND
www-data    34     1  0 21:46 ?        00:00:00 apache2 -DFOREGROUND
www-data    35     1  0 21:46 ?        00:00:00 apache2 -DFOREGROUND
www-data    36     1  0 21:46 ?        00:00:00 apache2 -DFOREGROUND
www-data    37     1  0 21:46 ?        00:00:00 apache2 -DFOREGROUND
www-data    38     1  0 21:46 ?        00:00:00 apache2 -DFOREGROUND
root        39     0  0 21:47 pts/0    00:00:00 /bin/bash
www-data    47     1  0 21:48 ?        00:00:00 apache2 -DFOREGROUND
root        66    39  0 22:11 pts/0    00:00:00 ps -ef
root@21e39f251a3a:/var/log/apt#

**Comment by bubbajames-docker** [comment]
Hi Hemdon,
Sorry for the delay in response.  

If starting image using Dockerfile, then you must provide your own database instance and configure environment variables according to README section "Using Dockerfile"

If starting using docker-compose, be sure you have pulled repository sample files which include sample database secret files.

**Comment by bubbajames-docker** [comment]
Closing due to no response.
