### ISSUE TITLE
Update to v5.0

### ISSUE THREAD

**Issue by HenkVanMaanen** [bubbajames-docker/sendy#3]
Hi, can you please update sendy to the new version v5.0.

I can provide the v5.0 if you don't have the necessary new license key, just hit me up.

**Comment by rynaardb** [comment]
It would be really nice to update to version 5.0. 

Any ETA as to when this might be possible?

**Comment by Svarto** [comment]
#6 I created a PR to update to 5.2

**Comment by bubbajames-docker** [comment]
Resolved with PR #6
